version: '3.4'

services:
  center_surround:
    image: activeloop_train
    build:
      context: .
    volumes:
      - .:/project
      - ./notebooks:/notebooks
      - /var/sinz-shared:/data
    env_file: .env
    runtime: nvidia